### PR TITLE
Fix build errors

### PR DESCRIPTION
**Pull request by alainmeier**

### CODE REVIEW

**Comment by alainmeier** [comment]
Ready for review @connorjacobsen

**Comment by alainmeier** [comment]
Note this changes the `json` return a little bit - it will now return a parsed JSON response instead of a string and it will return `nil` instead of empty string for body-less responses. I think these are improvements.

**Comment by alainmeier** [comment]
Also @connorjacobsen after merging could you release a point update to the gem?

**Comment by connorjacobsen** [comment]
@alainmeier Yep

**Comment by connorjacobsen** [comment]
@alainmeier Released

**Comment by alainmeier** [comment]
@javierjulio please note the change made in this PR - also the JSON return is now in version `0.5.2`

**Comment by javierjulio** [comment]
Hmm I'm not sure having it as parsed JSON is better/right. I'm not crazy about pushing for a change though. Perhaps my mistake was naming the property `json` since that's what I was focusing on, just getting the raw JSON value. Should have named it something like `response_body` or `raw_response_body`. To get the raw value I have to do for example `profile.json.to_json`. Not bad just felt it a little odd. I could have it named it better to start with. Thanks though for getting this out!

**Pull request merged**
